#!/bin/bash
set -eEuo pipefail

root_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." &>/dev/null && pwd)"
common_file_location="${root_dir}/ci/common.sh"
export PRE_PUSH_HOOK=true


####
# Checking all the requirement(s)
####
if ! [ -f "${common_file_location}" ]; then
  echo -e "\n\033[1;31mERROR: ${common_file_location} file is missing !!!  Exiting ...\033[0m\n"
  exit 1
else
  # shellcheck disable=SC1090
  source "${common_file_location}"
fi


####
# Main
####
log_debug "\n=== Pre-push hook start ==="
current_branch="$(git rev-parse --abbrev-ref HEAD)" || fn_die "ERROR: Failed to retrieve current GitHub branch using 'git rev-parse' command. Exiting ..."

if [[ "${current_branch}" != "main" ]] && ! [[ "${current_branch}" =~ ^release/.* ]]; then
  # Run the script and exit if failed to prevent git from pushing to upstream
  if ! "${root_dir}/ci/run_locally.sh"; then
    exit 1
  fi
fi


####
# End
####
log_debug "\n=== Pre-push hook end ==="
exit 0