[package]
authors.workspace = true
name = "cumulus-relay-chain-minimal-node"
version = "0.11.0"
edition.workspace = true
description = "Minimal node implementation to be used in tandem with RPC or light-client mode. (polkadot v1.10.0)"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
polkadot-primitives = { workspace = true }
polkadot-core-primitives = { workspace = true }
polkadot-overseer = { workspace = true }
polkadot-node-subsystem-util = { workspace = true }
polkadot-node-network-protocol = { workspace = true }
polkadot-availability-recovery = { workspace = true }
polkadot-collator-protocol = { workspace = true }
polkadot-network-bridge = { workspace = true }
polkadot-node-collation-generation = { workspace = true }
polkadot-node-core-runtime-api = { workspace = true }
polkadot-node-core-chain-api = { workspace = true }
polkadot-node-core-prospective-parachains = { workspace = true }
service = { workspace = true }
sc-authority-discovery = { workspace = true }
sc-network = { workspace = true }
sc-network-common = { workspace = true }
sc-service = { workspace = true }
sc-client-api = { workspace = true }
prometheus-endpoint = { workspace = true }
sc-tracing = { workspace = true }
sc-utils = { workspace = true }
sp-api = { workspace = true }
sp-consensus-babe = { workspace = true }
sp-consensus = { workspace = true }
sp-runtime = { workspace = true }
sp-blockchain = { workspace = true }
tokio = { version = "1.32.0", features = ["macros"] }
cumulus-relay-chain-interface = { workspace = true }
cumulus-relay-chain-rpc-interface = { workspace = true }
cumulus-primitives-core = { workspace = true }

array-bytes = "6.1"
tracing = "0.1.37"
async-trait = "0.1.79"
futures = "0.3.28"
parking_lot = "0.12.1"
