#!/bin/sh 
# shellcheck disable=SC2068

mkdir -p "${HOME}/.cargo/registry"

# Use rbuilder image to compile the source. All package and cargo cache are mapped on
# host's user folder. It also maps the .git-credential user file from the user in order
# to download dependencies from private repos.
# ${HOME}/.git-credentials should contain the following directive:
# https://<doesnt_mater>:<your-github-token>@github.com
#
# for example: https://aaaa:ghp_juippNBMadlkfkalk2082792LKjl3432@github.com

docker run --rm -ti \
    -v "${HOME}/.cargo/registry:/usr/local/cargo/registry" \
    -v "${HOME}/.git-credentials:/${HOME}/.git-credentials" \
    -v "${HOME}/.gitconfig:/${HOME}/.gitconfig" \
    -v "${HOME}/.git-credentials:/.git-credentials" \
    -v "${HOME}/.gitconfig:/.gitconfig" \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    -v .:/usr/src/node \
    -u "$(id -u):$(id -g)" \
    rbuilder \
    cargo $@
