[package]
name = "pallet-ultraplonk-verifier"
version = "0.1.0"
description = "A ultra plonk (noir-lang) verifier pallet implementation based on pallet-verifiers abstraction."
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license = "GPL-3.0"


[dependencies]
sp-core = { workspace = true }
sp-std = { workspace = true }
hp-verifiers = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-verifiers = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
log = "0.4.21"
hex-literal = { workspace = true, optional = true }
native = { workspace = true }
pallet-aggregate = { workspace = true, optional = true, default-features = false, features = [
    "runtime-benchmarks",
] }

[dev-dependencies]
hex-literal = { workspace = true }
serial_test = "3.1.1"
codec = { workspace = true, features = ["std"] }
sp-io = { workspace = true, features = ["std"] }
scale-info = { workspace = true }
sp-runtime = { workspace = true }
pallet-balances = { workspace = true, features = ["std", "runtime-benchmarks"] }

[features]
std = [
    "sp-core/std",
    "sp-std/std",
    "hp-verifiers/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-verifiers/std",
    "native/std",
    "pallet-balances/std",
]
default = ["std"]
runtime-benchmarks = [
    "dep:hex-literal",
    "dep:frame-benchmarking",
    "dep:pallet-aggregate",
    "pallet-verifiers/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
]
