[package]
name = "pallet-proofofsql-verifier"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-core = { workspace = true }
sp-std = { workspace = true }
hp-verifiers = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-verifiers = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
log = "0.4.21"
hex-literal = { workspace = true, optional = true }
native = { workspace = true }
codec = { workspace = true }
scale-info = { workspace = true }
derivative = { version = "2.2.0" }

[features]
default = ["std"]
std = [
    "sp-core/std",
    "frame-support/std",
    "frame-system/std",
    "hp-verifiers/std",
    "pallet-verifiers/std",
    "native/std",
    "codec/std",
    "scale-info/std",
]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "pallet-verifiers/runtime-benchmarks",
    "dep:hex-literal",
]