[package]
name = "pallet-proofofsql-verifier"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
proof-of-sql-verifier = { git = "https://github.com/HorizenLabs/proof-of-sql-verifier.git", default-features = false, rev = "2beb019030e104b2a0519a785d2a043db06435a6" }
log = "0.4.21"
hex-literal = { workspace = true, optional = true }
codec = { workspace = true }
scale-info = { workspace = true }
derivative = { version = "2.2.0" }

hp-verifiers = { workspace = true }
pallet-verifiers = { workspace = true }

frame-support = { workspace = true }
frame-system = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
sp-core = { workspace = true }
sp-std = { workspace = true }
sp-io = { workspace = true, optional = true }

[dev-dependencies]
rstest = { workspace = true }

[features]
default = ["std"]
std = [
    "proof-of-sql-verifier/std",
    "sp-core/std",
    "frame-support/std",
    "frame-system/std",
    "hp-verifiers/std",
    "pallet-verifiers/std",
    "codec/std",
    "scale-info/std",
]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "pallet-verifiers/runtime-benchmarks",
    "dep:hex-literal",
    "dep:sp-io",
]