[package]
name = "proofofsql"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
sp-core = { workspace = true }
sp-std = { workspace = true }
hp-verifiers = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-verifiers = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
log = "0.4.21"
hex-literal = { workspace = true, optional = true }
native = { workspace = true }