[package]
name = "pallet-proofofsql-verifier"
version = "0.1.0"
description = "A verifier pallet for SxT ProofOfSql proofs."
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license = "Apache-2.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
proof-of-sql-verifier = { git = "https://github.com/HorizenLabs/proof-of-sql-verifier.git", default-features = false, tag = "v0.2.0" }
log = "0.4.21"
hex-literal = { workspace = true, optional = true }
codec = { workspace = true }
scale-info = { workspace = true }
educe = { version = "0.6.0", default-features = false, features = [
    "Clone",
    "Debug",
    "PartialEq",
] }

hp-verifiers = { workspace = true }
pallet-verifiers = { workspace = true }

frame-support = { workspace = true }
frame-system = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
sp-core = { workspace = true }
sp-std = { workspace = true }
sp-io = { workspace = true, optional = true }
pallet-aggregate = { workspace = true, optional = true, default-features = false, features = [
    "runtime-benchmarks",
] }

[dev-dependencies]
rstest = { workspace = true }
pallet-balances = { workspace = true, features = ["std", "runtime-benchmarks"] }

[features]
default = ["std"]
std = [
    "proof-of-sql-verifier/std",
    "sp-core/std",
    "frame-support/std",
    "frame-system/std",
    "hp-verifiers/std",
    "pallet-verifiers/std",
    "codec/std",
    "scale-info/std",
    "pallet-balances/std",
]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "pallet-verifiers/runtime-benchmarks",
    "dep:hex-literal",
    "dep:sp-io",
    "dep:pallet-aggregate",
]
