[relaychain]
default_command = "zkv-relay"
default_args = []

chain = "local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 1000
chain_spec_path = "specs/horizen-chainspec.json"
add_to_genesis = true
cumulus_based = true
force_decorator = "generic-evm"

[[parachains.collators]]
name = "collator-alice"
command = "paratest-node"
args = []

[[parachains.collators]]
name = "collator-bob"
command = "paratest-node"
args = []
