[package]
name = "pallet-zksync-verifier"
version = "0.1.0"
description = "A zksync-era verifier pallet."
homepage.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license = "Apache-2.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
native = { workspace = true }
pallet-verifiers = { workspace = true }
hp-verifiers = { workspace = true }
hex-literal = { workspace = true, optional = true }

sp-core = { workspace = true, optional = true }
scale-info = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
pallet-aggregate = { workspace = true, optional = true, default-features = false, features = [
    "runtime-benchmarks",
] }

[dev-dependencies]
codec = { workspace = true, features = ["std"] }
sp-io = { workspace = true, features = ["std"] }
hex-literal = { workspace = true }
pallet-balances = { workspace = true, features = ["std", "runtime-benchmarks"] }

[features]
runtime-benchmarks = [
    "dep:hex-literal",
    "dep:frame-benchmarking",
    "dep:sp-core",
    "dep:pallet-aggregate",
    "pallet-verifiers/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
]
default = ["std"]
std = [
    "native/std",
    "scale-info/std",
    "pallet-verifiers/std",
    "frame-support/std",
]
try-runtime = ["pallet-verifiers/try-runtime", "frame-support/try-runtime"]
