DEFAULT_BM_STEPS=50
DEFAULT_BM_REPEAT=20
DEFAULT_BM_HEAP_PAGES=4096

# The following line ensure we know the project root
PROJECT_ROOT=${PROJECT_ROOT:-$(git rev-parse --show-toplevel)}
WEIGTH_OUT_PATH=${WEIGTH_OUT_PATH:-""}
NH_NODE_EXE=${NH_NODE_EXE:-"${PROJECT_ROOT}/target/production/nh-node"}
BM_STEPS=${BM_STEPS:-${DEFAULT_BM_STEPS}}
BM_REPEAT=${BM_REPEAT:-${DEFAULT_BM_REPEAT}}
BM_HEAP_PAGES=${BM_HEAP_PAGES:-${DEFAULT_BM_HEAP_PAGES}}
