// Copyright 2024, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_staking`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 36.0.0
//! DATE: 2024-09-24, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `4e8638f0fa13`, CPU: `AMD Ryzen 7 7700X 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /usr/local/bin/zkv-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet-staking
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /data/benchmark/HEADER-APACHE2
// --output
// /data/benchmark/runtime/src/weights/pallet_staking.rs
// --template
// /data/benchmark/node/zkv-deploy-weight-template.hbs
// --base-path=/tmp/tmp.f6luOFd200

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weights for `pallet_staking` using the zkVerify node and recommended hardware.
pub struct ZKVWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_staking::WeightInfo for ZKVWeight<T> {
    /// Storage: `Staking::Bonded` (r:1 w:1)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:1 w:1)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Locks` (r:1 w:1)
    /// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Freezes` (r:1 w:0)
    /// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Payee` (r:0 w:1)
    /// Proof: `Staking::Payee` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    fn bond() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `891`
        //  Estimated: `4764`
        // Minimum execution time: 41_180_000 picoseconds.
        Weight::from_parts(42_410_000, 4764)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:1 w:1)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Locks` (r:1 w:1)
    /// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Freezes` (r:1 w:0)
    /// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:3 w:3)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:2 w:2)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    fn bond_extra() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1773`
        //  Estimated: `8877`
        // Minimum execution time: 80_670_000 picoseconds.
        Weight::from_parts(82_361_000, 8877)
            .saturating_add(T::DbWeight::get().reads(9_u64))
            .saturating_add(T::DbWeight::get().writes(7_u64))
    }
    /// Storage: `Staking::Ledger` (r:1 w:1)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:1 w:0)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinNominatorBond` (r:1 w:0)
    /// Proof: `Staking::MinNominatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CurrentEra` (r:1 w:0)
    /// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Locks` (r:1 w:1)
    /// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Freezes` (r:1 w:0)
    /// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:3 w:3)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:2 w:2)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    fn unbond() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1978`
        //  Estimated: `8877`
        // Minimum execution time: 88_710_000 picoseconds.
        Weight::from_parts(90_350_000, 8877)
            .saturating_add(T::DbWeight::get().reads(12_u64))
            .saturating_add(T::DbWeight::get().writes(7_u64))
    }
    /// Storage: `Staking::Ledger` (r:1 w:1)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CurrentEra` (r:1 w:0)
    /// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Locks` (r:1 w:1)
    /// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Freezes` (r:1 w:0)
    /// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
    /// The range of component `s` is `[0, 100]`.
    fn withdraw_unbonded_update(s: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1031`
        //  Estimated: `4764`
        // Minimum execution time: 39_510_000 picoseconds.
        Weight::from_parts(40_584_439, 4764)
            // Standard Error: 517
            .saturating_add(Weight::from_parts(31_384, 0).saturating_mul(s.into()))
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Staking::Ledger` (r:1 w:1)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:1)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CurrentEra` (r:1 w:0)
    /// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::SlashingSpans` (r:1 w:1)
    /// Proof: `Staking::SlashingSpans` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Balances::Locks` (r:1 w:1)
    /// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Freezes` (r:1 w:0)
    /// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:1 w:0)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:1 w:1)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CounterForNominators` (r:1 w:1)
    /// Proof: `Staking::CounterForNominators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:2 w:2)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:1 w:1)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::CounterForListNodes` (r:1 w:1)
    /// Proof: `VoterList::CounterForListNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Payee` (r:0 w:1)
    /// Proof: `Staking::Payee` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    /// Storage: `Staking::SpanSlash` (r:0 w:100)
    /// Proof: `Staking::SpanSlash` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
    /// The range of component `s` is `[0, 100]`.
    fn withdraw_unbonded_kill(s: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1979 + s * (4 ±0)`
        //  Estimated: `6248 + s * (4 ±0)`
        // Minimum execution time: 83_100_000 picoseconds.
        Weight::from_parts(90_296_104, 6248)
            // Standard Error: 2_749
            .saturating_add(Weight::from_parts(1_356_984, 0).saturating_mul(s.into()))
            .saturating_add(T::DbWeight::get().reads(13_u64))
            .saturating_add(T::DbWeight::get().writes(11_u64))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
            .saturating_add(Weight::from_parts(0, 4).saturating_mul(s.into()))
    }
    /// Storage: `Staking::Ledger` (r:1 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinValidatorBond` (r:1 w:0)
    /// Proof: `Staking::MinValidatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinCommission` (r:1 w:0)
    /// Proof: `Staking::MinCommission` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:1 w:1)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MaxValidatorsCount` (r:1 w:0)
    /// Proof: `Staking::MaxValidatorsCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:1 w:0)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:1 w:1)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:1 w:1)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::CounterForListNodes` (r:1 w:1)
    /// Proof: `VoterList::CounterForListNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CounterForValidators` (r:1 w:1)
    /// Proof: `Staking::CounterForValidators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    fn validate() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1200`
        //  Estimated: `4339`
        // Minimum execution time: 50_650_000 picoseconds.
        Weight::from_parts(51_880_000, 4339)
            .saturating_add(T::DbWeight::get().reads(11_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }
    /// Storage: `Staking::Ledger` (r:1 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:128 w:128)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// The range of component `k` is `[1, 128]`.
    fn kick(k: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1853 + k * (379 ±0)`
        //  Estimated: `4339 + k * (2841 ±0)`
        // Minimum execution time: 28_230_000 picoseconds.
        Weight::from_parts(29_987_587, 4339)
            // Standard Error: 6_376
            .saturating_add(Weight::from_parts(5_726_669, 0).saturating_mul(k.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(k.into())))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(k.into())))
            .saturating_add(Weight::from_parts(0, 2841).saturating_mul(k.into()))
    }
    /// Storage: `Staking::Ledger` (r:1 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinNominatorBond` (r:1 w:0)
    /// Proof: `Staking::MinNominatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:1 w:1)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MaxNominatorsCount` (r:1 w:0)
    /// Proof: `Staking::MaxNominatorsCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:11 w:0)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CurrentEra` (r:1 w:0)
    /// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:2 w:2)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:1 w:1)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::CounterForListNodes` (r:1 w:1)
    /// Proof: `VoterList::CounterForListNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CounterForNominators` (r:1 w:1)
    /// Proof: `Staking::CounterForNominators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[1, 10]`.
    fn nominate(n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1739 + n * (96 ±0)`
        //  Estimated: `6248 + n * (2520 ±0)`
        // Minimum execution time: 63_780_000 picoseconds.
        Weight::from_parts(61_651_047, 6248)
            // Standard Error: 6_521
            .saturating_add(Weight::from_parts(3_459_187, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(12_u64))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(6_u64))
            .saturating_add(Weight::from_parts(0, 2520).saturating_mul(n.into()))
    }
    /// Storage: `Staking::Ledger` (r:1 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:1 w:0)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:1 w:1)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CounterForNominators` (r:1 w:1)
    /// Proof: `Staking::CounterForNominators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:2 w:2)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:1 w:1)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::CounterForListNodes` (r:1 w:1)
    /// Proof: `VoterList::CounterForListNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    fn chill() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1632`
        //  Estimated: `6248`
        // Minimum execution time: 54_980_000 picoseconds.
        Weight::from_parts(56_390_000, 6248)
            .saturating_add(T::DbWeight::get().reads(9_u64))
            .saturating_add(T::DbWeight::get().writes(6_u64))
    }
    /// Storage: `Staking::Ledger` (r:1 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Payee` (r:0 w:1)
    /// Proof: `Staking::Payee` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    fn set_payee() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `820`
        //  Estimated: `4339`
        // Minimum execution time: 20_040_000 picoseconds.
        Weight::from_parts(20_410_000, 4339)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Staking::Ledger` (r:1 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Payee` (r:1 w:1)
    /// Proof: `Staking::Payee` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    fn update_payee() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `887`
        //  Estimated: `4339`
        // Minimum execution time: 23_060_000 picoseconds.
        Weight::from_parts(23_680_000, 4339)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Staking::Bonded` (r:1 w:1)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:2 w:2)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    fn set_controller() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `820`
        //  Estimated: `7688`
        // Minimum execution time: 22_950_000 picoseconds.
        Weight::from_parts(23_530_000, 7688)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `Staking::ValidatorCount` (r:0 w:1)
    /// Proof: `Staking::ValidatorCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    fn set_validator_count() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_020_000 picoseconds.
        Weight::from_parts(2_170_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Staking::ForceEra` (r:0 w:1)
    /// Proof: `Staking::ForceEra` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    fn force_no_eras() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_970_000 picoseconds.
        Weight::from_parts(6_360_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Staking::ForceEra` (r:0 w:1)
    /// Proof: `Staking::ForceEra` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    fn force_new_era() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_950_000 picoseconds.
        Weight::from_parts(6_390_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Staking::ForceEra` (r:0 w:1)
    /// Proof: `Staking::ForceEra` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    fn force_new_era_always() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_830_000 picoseconds.
        Weight::from_parts(6_270_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Staking::Invulnerables` (r:0 w:1)
    /// Proof: `Staking::Invulnerables` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// The range of component `v` is `[0, 1000]`.
    fn set_invulnerables(v: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_150_000 picoseconds.
        Weight::from_parts(2_561_554, 0)
            // Standard Error: 16
            .saturating_add(Weight::from_parts(8_718, 0).saturating_mul(v.into()))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Staking::Ledger` (r:2 w:2)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:1)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Payee` (r:1 w:0)
    /// Proof: `Staking::Payee` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    /// The range of component `i` is `[0, 1]`.
    fn deprecate_controller_batch(i: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0 + i * (887 ±0)`
        //  Estimated: `3844 + i * (3844 ±0)`
        // Minimum execution time: 3_580_000 picoseconds.
        Weight::from_parts(4_045_522, 3844)
            // Standard Error: 21_762
            .saturating_add(Weight::from_parts(26_723_477, 0).saturating_mul(i.into()))
            .saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(i.into())))
            .saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(i.into())))
            .saturating_add(Weight::from_parts(0, 3844).saturating_mul(i.into()))
    }
    /// Storage: `Staking::SlashingSpans` (r:1 w:1)
    /// Proof: `Staking::SlashingSpans` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Staking::Bonded` (r:1 w:1)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:1 w:1)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Locks` (r:1 w:1)
    /// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Freezes` (r:1 w:0)
    /// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:1 w:0)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:1 w:1)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CounterForNominators` (r:1 w:1)
    /// Proof: `Staking::CounterForNominators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:2 w:2)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:1 w:1)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::CounterForListNodes` (r:1 w:1)
    /// Proof: `VoterList::CounterForListNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Payee` (r:0 w:1)
    /// Proof: `Staking::Payee` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    /// Storage: `Staking::SpanSlash` (r:0 w:100)
    /// Proof: `Staking::SpanSlash` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
    /// The range of component `s` is `[0, 100]`.
    fn force_unstake(s: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1979 + s * (4 ±0)`
        //  Estimated: `6248 + s * (4 ±0)`
        // Minimum execution time: 78_270_000 picoseconds.
        Weight::from_parts(87_170_947, 6248)
            // Standard Error: 5_406
            .saturating_add(Weight::from_parts(1_320_160, 0).saturating_mul(s.into()))
            .saturating_add(T::DbWeight::get().reads(13_u64))
            .saturating_add(T::DbWeight::get().writes(12_u64))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
            .saturating_add(Weight::from_parts(0, 4).saturating_mul(s.into()))
    }
    /// Storage: `Staking::UnappliedSlashes` (r:1 w:1)
    /// Proof: `Staking::UnappliedSlashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `s` is `[1, 1000]`.
    fn cancel_deferred_slash(s: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `66592`
        //  Estimated: `70057`
        // Minimum execution time: 79_600_000 picoseconds.
        Weight::from_parts(793_091_261, 70057)
            // Standard Error: 51_950
            .saturating_add(Weight::from_parts(4_403_704, 0).saturating_mul(s.into()))
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Staking::Bonded` (r:65 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:65 w:65)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ErasStakersClipped` (r:1 w:0)
    /// Proof: `Staking::ErasStakersClipped` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Staking::ErasStakersOverview` (r:1 w:0)
    /// Proof: `Staking::ErasStakersOverview` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ClaimedRewards` (r:1 w:1)
    /// Proof: `Staking::ClaimedRewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Staking::CurrentEra` (r:1 w:0)
    /// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ErasValidatorReward` (r:1 w:0)
    /// Proof: `Staking::ErasValidatorReward` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Locks` (r:65 w:65)
    /// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Freezes` (r:65 w:0)
    /// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:65 w:65)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ErasStakersPaged` (r:1 w:0)
    /// Proof: `Staking::ErasStakersPaged` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Staking::ErasRewardPoints` (r:1 w:0)
    /// Proof: `Staking::ErasRewardPoints` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Staking::ErasValidatorPrefs` (r:1 w:0)
    /// Proof: `Staking::ErasValidatorPrefs` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Payee` (r:65 w:0)
    /// Proof: `Staking::Payee` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[0, 64]`.
    fn payout_stakers_alive_staked(n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `8017 + n * (396 ±0)`
        //  Estimated: `10595 + n * (3774 ±0)`
        // Minimum execution time: 126_381_000 picoseconds.
        Weight::from_parts(160_173_350, 10595)
            // Standard Error: 30_692
            .saturating_add(Weight::from_parts(40_098_845, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(14_u64))
            .saturating_add(T::DbWeight::get().reads((6_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(4_u64))
            .saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 3774).saturating_mul(n.into()))
    }
    /// Storage: `Staking::Ledger` (r:1 w:1)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Locks` (r:1 w:1)
    /// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Freezes` (r:1 w:0)
    /// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:3 w:3)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:2 w:2)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// The range of component `l` is `[1, 32]`.
    fn rebond(l: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1774 + l * (7 ±0)`
        //  Estimated: `8877`
        // Minimum execution time: 77_341_000 picoseconds.
        Weight::from_parts(79_966_446, 8877)
            // Standard Error: 2_384
            .saturating_add(Weight::from_parts(126_708, 0).saturating_mul(l.into()))
            .saturating_add(T::DbWeight::get().reads(9_u64))
            .saturating_add(T::DbWeight::get().writes(7_u64))
    }
    /// Storage: `Staking::Bonded` (r:1 w:1)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:1 w:1)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::SlashingSpans` (r:1 w:1)
    /// Proof: `Staking::SlashingSpans` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Balances::Locks` (r:1 w:1)
    /// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Freezes` (r:1 w:0)
    /// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:1 w:0)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:1 w:1)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CounterForNominators` (r:1 w:1)
    /// Proof: `Staking::CounterForNominators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:2 w:2)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:1 w:1)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::CounterForListNodes` (r:1 w:1)
    /// Proof: `VoterList::CounterForListNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Payee` (r:0 w:1)
    /// Proof: `Staking::Payee` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    /// Storage: `Staking::SpanSlash` (r:0 w:100)
    /// Proof: `Staking::SpanSlash` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
    /// The range of component `s` is `[1, 100]`.
    fn reap_stash(s: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1979 + s * (4 ±0)`
        //  Estimated: `6248 + s * (4 ±0)`
        // Minimum execution time: 88_691_000 picoseconds.
        Weight::from_parts(100_597_660, 6248)
            // Standard Error: 17_016
            .saturating_add(Weight::from_parts(1_222_828, 0).saturating_mul(s.into()))
            .saturating_add(T::DbWeight::get().reads(12_u64))
            .saturating_add(T::DbWeight::get().writes(11_u64))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
            .saturating_add(Weight::from_parts(0, 4).saturating_mul(s.into()))
    }
    /// Storage: `VoterList::CounterForListNodes` (r:1 w:0)
    /// Proof: `VoterList::CounterForListNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:147 w:0)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:110 w:0)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:110 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:110 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:110 w:0)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:11 w:0)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CounterForValidators` (r:1 w:0)
    /// Proof: `Staking::CounterForValidators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ValidatorCount` (r:1 w:0)
    /// Proof: `Staking::ValidatorCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinimumValidatorCount` (r:1 w:0)
    /// Proof: `Staking::MinimumValidatorCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CurrentEra` (r:1 w:1)
    /// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ErasValidatorPrefs` (r:0 w:10)
    /// Proof: `Staking::ErasValidatorPrefs` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ErasStakersPaged` (r:0 w:20)
    /// Proof: `Staking::ErasStakersPaged` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Staking::ErasStakersOverview` (r:0 w:10)
    /// Proof: `Staking::ErasStakersOverview` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ErasTotalStake` (r:0 w:1)
    /// Proof: `Staking::ErasTotalStake` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ErasStartSessionIndex` (r:0 w:1)
    /// Proof: `Staking::ErasStartSessionIndex` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinimumActiveStake` (r:0 w:1)
    /// Proof: `Staking::MinimumActiveStake` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// The range of component `v` is `[1, 10]`.
    /// The range of component `n` is `[0, 100]`.
    fn new_era(v: u32, n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0 + n * (718 ±0) + v * (3596 ±0)`
        //  Estimated: `376869 + n * (3349 ±0) + v * (3349 ±0)`
        // Minimum execution time: 492_981_000 picoseconds.
        Weight::from_parts(497_210_000, 376869)
            // Standard Error: 1_844_609
            .saturating_add(Weight::from_parts(59_968_480, 0).saturating_mul(v.into()))
            // Standard Error: 183_805
            .saturating_add(Weight::from_parts(19_501_586, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(153_u64))
            .saturating_add(T::DbWeight::get().reads((5_u64).saturating_mul(v.into())))
            .saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(8_u64))
            .saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(v.into())))
            .saturating_add(Weight::from_parts(0, 3349).saturating_mul(n.into()))
            .saturating_add(Weight::from_parts(0, 3349).saturating_mul(v.into()))
    }
    /// Storage: `VoterList::CounterForListNodes` (r:1 w:0)
    /// Proof: `VoterList::CounterForListNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:147 w:0)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:6000 w:0)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:6000 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:6000 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:6000 w:0)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:1000 w:0)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinimumActiveStake` (r:0 w:1)
    /// Proof: `Staking::MinimumActiveStake` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// The range of component `v` is `[500, 1000]`.
    /// The range of component `n` is `[2500, 5000]`.
    fn get_npos_voters(v: u32, n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `2223 + n * (717 ±0) + v * (393 ±0)`
        //  Estimated: `376869 + n * (3349 ±0) + v * (3349 ±0)`
        // Minimum execution time: 90_874_777_000 picoseconds.
        Weight::from_parts(91_140_137_000, 376869)
            // Standard Error: 208_280
            .saturating_add(Weight::from_parts(18_578_228, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(148_u64))
            .saturating_add(T::DbWeight::get().reads((5_u64).saturating_mul(v.into())))
            .saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(1_u64))
            .saturating_add(Weight::from_parts(0, 3349).saturating_mul(n.into()))
            .saturating_add(Weight::from_parts(0, 3349).saturating_mul(v.into()))
    }
    /// Storage: `Staking::CounterForValidators` (r:1 w:0)
    /// Proof: `Staking::CounterForValidators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:1001 w:0)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// The range of component `v` is `[500, 1000]`.
    fn get_npos_targets(v: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `899 + v * (50 ±0)`
        //  Estimated: `3510 + v * (2520 ±0)`
        // Minimum execution time: 2_555_001_000 picoseconds.
        Weight::from_parts(103_586_214, 3510)
            // Standard Error: 11_614
            .saturating_add(Weight::from_parts(4_976_475, 0).saturating_mul(v.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(v.into())))
            .saturating_add(Weight::from_parts(0, 2520).saturating_mul(v.into()))
    }
    /// Storage: `Staking::MinCommission` (r:0 w:1)
    /// Proof: `Staking::MinCommission` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinValidatorBond` (r:0 w:1)
    /// Proof: `Staking::MinValidatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MaxValidatorsCount` (r:0 w:1)
    /// Proof: `Staking::MaxValidatorsCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MaxStakedRewards` (r:0 w:1)
    /// Proof: `Staking::MaxStakedRewards` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ChillThreshold` (r:0 w:1)
    /// Proof: `Staking::ChillThreshold` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MaxNominatorsCount` (r:0 w:1)
    /// Proof: `Staking::MaxNominatorsCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinNominatorBond` (r:0 w:1)
    /// Proof: `Staking::MinNominatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn set_staking_configs_all_set() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_860_000 picoseconds.
        Weight::from_parts(4_120_000, 0)
            .saturating_add(T::DbWeight::get().writes(7_u64))
    }
    /// Storage: `Staking::MinCommission` (r:0 w:1)
    /// Proof: `Staking::MinCommission` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinValidatorBond` (r:0 w:1)
    /// Proof: `Staking::MinValidatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MaxValidatorsCount` (r:0 w:1)
    /// Proof: `Staking::MaxValidatorsCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MaxStakedRewards` (r:0 w:1)
    /// Proof: `Staking::MaxStakedRewards` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ChillThreshold` (r:0 w:1)
    /// Proof: `Staking::ChillThreshold` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MaxNominatorsCount` (r:0 w:1)
    /// Proof: `Staking::MaxNominatorsCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinNominatorBond` (r:0 w:1)
    /// Proof: `Staking::MinNominatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn set_staking_configs_all_remove() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_450_000 picoseconds.
        Weight::from_parts(3_610_000, 0)
            .saturating_add(T::DbWeight::get().writes(7_u64))
    }
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:1 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:1 w:1)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ChillThreshold` (r:1 w:0)
    /// Proof: `Staking::ChillThreshold` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MaxNominatorsCount` (r:1 w:0)
    /// Proof: `Staking::MaxNominatorsCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CounterForNominators` (r:1 w:1)
    /// Proof: `Staking::CounterForNominators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinNominatorBond` (r:1 w:0)
    /// Proof: `Staking::MinNominatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:1 w:0)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:2 w:2)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:1 w:1)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::CounterForListNodes` (r:1 w:1)
    /// Proof: `VoterList::CounterForListNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    fn chill_other() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1768`
        //  Estimated: `6248`
        // Minimum execution time: 70_040_000 picoseconds.
        Weight::from_parts(71_681_000, 6248)
            .saturating_add(T::DbWeight::get().reads(12_u64))
            .saturating_add(T::DbWeight::get().writes(6_u64))
    }
    /// Storage: `Staking::MinCommission` (r:1 w:0)
    /// Proof: `Staking::MinCommission` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:1 w:1)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    fn force_apply_min_commission() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `610`
        //  Estimated: `3510`
        // Minimum execution time: 12_580_000 picoseconds.
        Weight::from_parts(13_040_000, 3510)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Staking::MinCommission` (r:0 w:1)
    /// Proof: `Staking::MinCommission` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    fn set_min_commission() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_030_000 picoseconds.
        Weight::from_parts(2_240_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Balances::Locks` (r:1 w:1)
    /// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:1)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:1 w:1)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Freezes` (r:1 w:0)
    /// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
    fn restore_ledger() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `967`
        //  Estimated: `4764`
        // Minimum execution time: 42_941_000 picoseconds.
        Weight::from_parts(44_260_000, 4764)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
}
