[package]
authors.workspace = true
name = "cumulus-relay-chain-inprocess-interface"
version = "0.11.0"
edition.workspace = true
description = "Implementation of the RelayChainInterface trait for Polkadot full-nodes. (polkadot v1.10.0)"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
async-trait = "0.1.79"
futures = "0.3.28"
futures-timer = "3.0.2"
sc-cli = { workspace = true }
sc-client-api = { workspace = true }
sc-telemetry = { workspace = true }
sc-tracing = { workspace = true }
sc-sysinfo = { workspace = true }
sp-api = { workspace = true }
sp-consensus = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-state-machine = { workspace = true }

# Polkadot
zkv-cli = { workspace = true, default-features = false, features = ["cli"] }

service = { workspace = true }
cumulus-primitives-core = { workspace = true }
cumulus-relay-chain-interface = { workspace = true }

[dev-dependencies]
sp-keyring = { workspace = true }
polkadot-primitives = { workspace = true, default-features = true }
test-client = { path = "../../../../relay-node/test/client" }
metered = { package = "prioritized-metered-channel", version = "0.5.1", default-features = false, features = [
    "futures_channel",
] }
# cumulus-test-service = { path = "../../test/service" }
