[package]
authors.workspace = true
name = "cumulus-relay-chain-inprocess-interface"
version = "0.17.0"
edition.workspace = true
description = "Implementation of the RelayChainInterface trait for Polkadot full-nodes. (polkadot v1.15.0)"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
async-trait = { workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
sc-cli.workspace = true
sc-cli.default-features = true
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-telemetry.workspace = true
sc-telemetry.default-features = true
sc-tracing.workspace = true
sc-tracing.default-features = true
sc-sysinfo.workspace = true
sc-sysinfo.default-features = true
sp-api.workspace = true
sp-api.default-features = true
sp-consensus.workspace = true
sp-consensus.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-state-machine.workspace = true
sp-state-machine.default-features = true
zkv-cli = { workspace = true, features = ["cli"] }
# service is our own zkv-service (see workspace)
service = { workspace = true }
cumulus-primitives-core.workspace = true
cumulus-primitives-core.default-features = true
cumulus-relay-chain-interface.workspace = true
cumulus-relay-chain-interface.default-features = true

[dev-dependencies]
sp-keyring = { workspace = true }
polkadot-primitives = { workspace = true, default-features = true }
test-client = { path = "../../../../relay-node/test/client" }
metered = { features = ["futures_channel"], workspace = true }
