[package]
name = "pallet-risc0-verifier"
version = "0.1.0"
description = "A risc0 verifier pallet"
homepage.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license = "Apache-2.0"

[dependencies]
log = "0.4.21"
hex-literal = { workspace = true, optional = true }

hp-verifiers = { workspace = true }
pallet-verifiers = { workspace = true }
native = { workspace = true }

sp-core = { workspace = true }
sp-std = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }

[dev-dependencies]
hex-literal = { workspace = true }

[features]
std = [
    "hp-verifiers/std",
    "pallet-verifiers/std",
    "sp-std/std",
    "sp-core/std",
    "frame-support/std",
    "frame-system/std",
    "native/std",
]
default = ["std"]
runtime-benchmarks = [
    "dep:hex-literal",
    "dep:frame-benchmarking",
    "pallet-verifiers/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
]
