name: Build

run-name: "Workflow CI/CD Steps: build, unit and integration testing"

on:
  workflow_call:
    inputs:
      CACHING_MODE:
        required: true
        type: string
        
env:
  IMAGE_NAME: zencash/sc-ci-base
  IMAGE_TAG: noble_rust-stable_latest
  DOCKER_COMPOSE_CMD: "docker compose -f ${GITHUB_WORKSPACE}/ci/docker-compose.yml run --rm cargo-container"
  DOCKER_BUILD_DIR: /build
  DOCKER_CARGO_HOME: /tmp/.cargo
  CMAKE_INSTALL: true
  LLD_INSTALL: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up deps cache
        run: mkdir deps

      - name: Restore common cache
        if: ${{ !env.ACT && inputs.CACHING_MODE == 'CACHE_RESTORE' }}
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            deps/
          key: common-cache
    
      - name: Restore build cache
        if: ${{ !env.ACT && inputs.CACHING_MODE == 'CACHE_RESTORE' }}
        uses: actions/cache/restore@v3
        with:
          path: |
            target/
          key: build-cache

      - name: Set docker env vars
        run: |
          echo "USER_ID=$(id -u)" >> $GITHUB_ENV
          echo "GRP_ID=$(id -g)" >> $GITHUB_ENV

      - name: Cargo build
        run: ${{ env.DOCKER_COMPOSE_CMD }} cargo build --release

      - name: Save common cache
        if: ${{ !env.ACT && inputs.CACHING_MODE == 'CACHE_SAVE' }}
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            deps/
          key: common-cache
    
      - name: Save build cache
        if: ${{ !env.ACT && inputs.CACHING_MODE == 'CACHE_SAVE' }}
        uses: actions/cache/save@v3
        with:
          path: |
            target/
          key: build-cache