name: Pre Release Orchestrator

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  execute-system-tests:
    name: Execute System Tests
    uses: HorizenLabs/zkVerify-qa/.github/workflows/CI-e2e-tests.yml@main
    with:
      zkverify_version: ${{ github.ref_name }}
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      QA_SLACK_WEBHOOK_URL: ${{ secrets.QA_SLACK_WEBHOOK_URL }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    needs: execute-system-tests # Wait for e2e tests to finish

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0 # Necessary for git operations in setup_env.sh

      - name: Get Short Commit Hash
        id: get_short_commit_hash
        run: |
          echo "short_commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Environment Variables and Build
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKER_IMAGE_BUILD_NAME: zkverify-dev
          GITHUB_REF_NAME: ${{ github.ref_name }}
          COMMIT_HASH: ${{ steps.get_short_commit_hash.outputs.short_commit_hash }}

        run: |
          # Source the setup script to set up environment
          source "${GITHUB_WORKSPACE}/ci/setup_env.sh"

          # Set TEST_RELEASE to true to build and publish the dev docker image to private repo
          export TEST_RELEASE="true"

          # Run the docker build and publish script
          "${GITHUB_WORKSPACE}/ci/docker.sh"
