name: System Tests and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  execute-system-tests:
    uses: HorizenLabs/zkVerify-qa/.github/workflows/CI-e2e-tests.yml@main
    with:
      # Provide necessary inputs for the reusable workflow
      some_input: value
    secrets:
      # Pass any required secrets to the reusable workflow
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
