name: System Tests and Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/web3-943-post-merge-pipeline
    tags:
      - "*"

permissions:
  contents: read

jobs:
  get-commit-hash:
    runs-on: ubuntu-latest
    needs: execute-system-tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Commit Hash
        id: get_commit_hash
        run: |
          echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  execute-system-tests:
    uses: HorizenLabs/zkVerify-qa/.github/workflows/CI-e2e-tests.yml@main
    with:
      zkverify_tag: ${{ github.event.inputs.zkverify_tag || 'latest' }}
      zkverify_branch: ${{ github.event.inputs.zkverify_branch || 'main' }}
    secrets:
      DOCKER_HUB_USERNAME: test
      DOCKER_HUB_TOKEN: test
      QA_SLACK_WEBHOOK_URL: test
      GH_TOKEN: test

  # publish-docker:
  #   runs-on: ubuntu-latest
  #   needs: [execute-system-tests, get-commit-hash]
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Publish Docker Image
  #       run: |
  #         # Your Docker publish commands here
