name: System Tests and Publish Docker Image # Correctly placed at the top

on:
  workflow_dispatch: # Enables manual triggering
  push:
    branches:
      - main
      - feat/web3-943-post-merge-pipeline
    tags:
      - "*" # Triggers on pushes to main or any tag

permissions:
  contents: read
  id-token: write

jobs:
  execute-system-tests:
    uses: HorizenLabs/zkVerify-qa/.github/workflows/CI-e2e-tests.yml@main
    with:
      some_input: value # Replace with actual inputs
    secrets:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

  get-commit-hash:
    runs-on: ubuntu-latest
    needs: execute-system-tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Commit Hash
        id: get_commit_hash
        run: |
          echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  publish-docker:
    runs-on: ubuntu-latest
    needs: [execute-system-tests, get-commit-hash]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Publish Docker Image
        run: |
          # Your Docker publish commands here
